/**
	-- DO NOT EDIT !! GENERATED BY THE RUNNING THE PROGRAM SCLEX ON A VALID SPECIFICATION FILE --
	-- TO MAKE CHANGES TO THIS FILE PLEASE SEE THE DEVELOPER DOCUMENTATION AND SOURCE CODE --

	Lexer Generated from the Lexical Analyzer Generator - sclex */
#include <stdlib.h>
#include <stdio.h>
#include "buffer.h"
/* Function Prototype

	int sclex(FILE* infile);

Functionality: The lexer, will start to tokenized a files input and return the tokens found or an error
	sclex also will setup the recognized token into a temporary data structure where its information
	can be processed and stored for later use.

Parameters: FILE * infile points to a file given as an argument on the command line

Returns: returns a token found or an error. stores input recognized for use by parent
	function

Results: input stream is traversed and tokenized. The found lexeme is stored in a temp-
orary variable */
int sclex(FILE* scl_infile);
/* Function Prototype

	int get_id_for_symbol(char c);

Functionality: give the alphabet symbol depending on the  current
	input symbol. Or return an error

Parameters: a character c

Returns: an integer representation of a known alphabet symbol, or an error

Results: either a symbol representation for the alphabet character is returned
	 or an error, for further processing. */
int get_id_for_symbol(char scl_c);
/* Function Prototype

	int is_in_final_states(int state);

Functionality: By a given state number as an integer, decided
	whether the state is part of a final state and the DFA
	can potentially finish. The answer is returned as either
	1(False) or 0(True).

Parameters: an integer representation of a DFA state

Returns: an integer representation for BOOL 

Results: decides whether our input state is in the final state
	set or not and return the answer to the caller */
int is_in_final_states(int scl_state);

/* \#\0\# tokens are replaced by different things in the file */

/* replaced below will be the first part of the specification file
	 declarations and source code includes */

#include <stdio.h>
#include "scy.tab.h"
	/* declarations */
	int a;
													// lexfile.decs
/* alphabet size, number of states of the DFA, accept_size defines the
 number of final states that we accept on, num_regex defines the number
 of actual regular expressions the DFA recognizes */
#define scl_asize 70 						//dfa->alphabet->used
#define scl_tsize 6						//dfa->num_states
#define scl_accept_size 5					//dfa->Fstates->used
#define scl_num_regex 4					//dfa->num_re
	 /* The alphabet array */
	 const static char scl_al[scl_asize] = { '\t', '\n', ' ', '(', ')', '*', '+', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'	};
	 /* The DFA movement table */
	 const static int scl_table[scl_asize][scl_tsize] = {  {2,2,-1,-1,-1,-1},
{2,2,-1,-1,-1,-1},
{2,2,-1,-1,-1,-1},
{3,-1,-1,-1,-1,-1},
{3,-1,-1,-1,-1,-1},
{3,-1,-1,-1,-1,-1},
{3,-1,-1,-1,-1,-1},
{4,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{5,-1,-1,-1,5,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6},
{6,-1,-1,-1,-1,6}
 };
	 /* Final states array - what states we accept on */
	 const static int scl_accepted[scl_accept_size] = {  2,3,4,5,6 };
	 /* which regular expression is attached to which accepting states */
	 const static int scl_each_re_accepted[scl_num_regex][scl_accept_size] = { {2},
{3},
{6},
{4,5}
 };
	 /* The buffer we use to buffer the input file */
	 static buffer * scl_dbuf; 
	 /* The temporary text buffer we use to store the matched text, lexeme
	 	and make it available to the caller function */
	 char sctext[100];
	 /* The length of the matched lexeme to the regular expression pattern */
	 static int scleng;

	 /* As defined above */
int sclex(FILE* scl_infile){
	
	 char *scl_endmatch;
	 /*
	 accepted = tells whether we have moved into an accept state
	 failed = we have failed on the input somehow
	 s = current state we are in
	 last = last state - we came from
	 done = whether we have actually finished or not
	 count =
	 id =
	 c = current input character
	 */
	 int scl_s, scl_last, scl_failed, scl_accepted, scl_count,scl_done,scl_id;
	 char scl_c;
	 scl_done = 1;
	 /* Come back to this label when we need go back to state 0 of the DFA
	 	and reset some other variables */
dstart:
	/* Start at state 0 */
	 scl_s = scl_failed = scl_count = 0;
	 /* BOOL is somewhat reversed, and accepted 1 is false, 0 true */
	 scl_accepted = 1;
	 scl_last = scl_s;
	 /* only call and initialize buffer once */
	 if(scl_dbuf == NULL)
		 scl_dbuf = buffer_from_file(scl_infile);
	 /* point to back buffer pointer to keep track of fully found lexeme during
	 	parsing algorithm */
	 scl_endmatch = scl_dbuf->back;
	 scl_c = getchar(scl_dbuf);
	 /* Only truly finish when done is true(1) */
	 while(scl_done != 0){
		 /*  Either we have failed with an error, return the error token
		 	or we're done we can't match, return the actual character
		 	we can't match */
		 if(scl_accepted ==1 && scl_failed ==1 && scl_s == 0){
			 if(scl_done !=0){
				 return -1;
			 }
			 return scl_c;
		}
		/* we're in an accept state and haven't flagged a failure yet */
		if(scl_accepted == 0 && scl_failed == 1){
			/* store any matched input into our temporary character buffer */
			for(char *j=scl_dbuf->back;j<=scl_endmatch;j++){
				sctext[scl_count] = *j;
				scl_count++;
			}
			/* NULL terminate the string */
			sctext[scl_count] = '\0';
			/* set the temporary lexem length for users to use */
		    scleng = scl_count;
			/* with some ugly programming, reset the cursors for continuing to 
				read the rest of the input stream */
			scl_dbuf->back = scl_endmatch+1;
			scl_endmatch = scl_dbuf->back;
			scl_c = ungetchar(scl_dbuf);
			scl_c = ungetchar(scl_dbuf);
			scl_c = getchar(scl_dbuf);
			/* Find out which regular expression we just matched and then run its 
				associated code that was included with the regular expression pattern
				inside the specification file. */
			for(int n=0;n<scl_num_regex;n++){
				for(int m=0;m<scl_accept_size;m++){
					if(scl_each_re_accepted[n][m]-1 == scl_s){
						/* Below we run the user-defined code */
						switch(n){
							case 0:
								{
}
								break;
							case 1:
								{
	switch(sctext[0]){
		case '*':
			return TIMES;
		case '+':
			return PLUS;
		case ')':
			return RPAREN;
		case '(':
			return LPAREN;
	}
}
								break;
							case 2:
								{
	return IDENT;
}
								break;
							case 3:
								{
	return INTEGER;
}
								break;
							}

						/* The user-defined code is finished, reset the buffer and DFA
							to continue and jump back start of the DFA with goto dstart */
						if(*scl_dbuf->forward == EOF || *scl_dbuf->forward == '\0')
							scl_done = 0;
						
						goto dstart;
						
					}
				}
			}
			/* Error somehow we said we finished and accepted but no regular expression 
				has this state as a finish state */
			printf("couldn't find this finish state in any regular expression? wierd?\n");
			return 0;
			
		}
	 	scl_last = scl_s;
		/* get next state to move to for the current input character */
		scl_id = get_id_for_symbol(scl_c);
		if( scl_id != -1)
		    scl_s = scl_table[scl_id][scl_s]-1;
		/* error pass it on */
		else
		    scl_s = -1;
		/* are we in an accept state and we haven't found a failure then return 0 */
		if(is_in_final_states(scl_s) == 0){
			if(scl_accepted == 0 && scl_failed == 1){
				return 0;
			}
			/* we may have reached a failure and aren't really done so reset to 
				try to match for another token */
			scl_accepted = 0;
			scl_endmatch = scl_dbuf->forward -1;
		}
		/* we are in an existing state, continue to run */
		if(scl_s >= 0 && scl_s < scl_tsize){
			scl_c = getchar(scl_dbuf);
		    scl_endmatch++;
		}
		/* we aren't in an appropriate state for some reason so we need to try and
			recover somehow */
		else{
			/* we didn't fail but we are in a weird state, recover, print the character
				we couldn't match to standard output and reset DFA back to state 0 */
		    if(scl_failed == 1){
			   printf("%c",scl_c);
			   scl_c = getchar(scl_dbuf);
			   scl_s=0;
			   scl_last = 0;
			   scl_dbuf->back++;
			   scl_endmatch++;
			   scl_failed = 0;
		    }
			/* we failed so go back a state, reset the failed flag and back buffer pointer */
		    else{
			   scl_s = scl_last;
			   scl_failed = 1;
			   scl_endmatch--;
		    }
		}
	 }
	 /* Premature end of file or null character found so we return an error token */
    	if(scl_c == '\0' || scl_c == EOF)
	    return -1;
		/* all else fails we return the current input character we couldn't make any
			sense of. */
	 return scl_c;
 }

 /* As defined above */
int get_id_for_symbol(char scl_c){
	for(int a=0;a< scl_asize;a++){
		if(scl_al[a] == scl_c)
			return a;
	}
	return -1;
}

 /* As defined above */
int is_in_final_states(int scl_state){
	for(int r=0;r<scl_accept_size;r++){
		if(scl_accepted[r]-1 == scl_state)
			return 0;
	}
	return 1;
}
